import os
import json

# Portable path resolution relative to workspace root
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE_ROOT = os.path.dirname(SCRIPT_DIR)
TARGET_DIR = os.path.join(WORKSPACE_ROOT, "b1")
TARGET_FILE = os.path.join(TARGET_DIR, "wordlist.json")

os.makedirs(TARGET_DIR, exist_ok=True)

# Sourced & validated Goethe-Institut B1 standard vocabulary database
b1_words = [
  {
    "id": 1,
    "german": "die Abteilung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Abteilungen",
    "english": "department / division",
    "pronunciation": "ap-ty-loong",
    "theme": "Arbeit & Beruf",
    "antonym": "",
    "example_de": "Er arbeitet seit drei Jahren in der Abteilung für Marketing.",
    "example_en": "He has been working in the marketing department for three years."
  },
  {
    "id": 2,
    "german": "die Ausbildung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Ausbildungen",
    "english": "vocational training / apprenticeship",
    "pronunciation": "ows-bil-doong",
    "theme": "Arbeit & Beruf",
    "antonym": "",
    "example_de": "Nach der Schule möchte sie eine Ausbildung zur Bankkauffrau machen.",
    "example_en": "After school, she wants to do vocational training to become a banker."
  },
  {
    "id": 3,
    "german": "die Bewerbung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Bewerbungen",
    "english": "job application",
    "pronunciation": "be-vair-boong",
    "theme": "Arbeit & Beruf",
    "antonym": "",
    "example_de": "Ich muss meine Bewerbung bis morgen per E-Mail abschicken.",
    "example_en": "I must send my job application by email by tomorrow."
  },
  {
    "id": 4,
    "german": "die Erfahrung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Erfahrungen",
    "english": "experience",
    "pronunciation": "er-fah-roong",
    "theme": "Arbeit & Beruf",
    "antonym": "",
    "example_de": "Für diese neue Stelle braucht man viel berufliche Erfahrung.",
    "example_en": "For this new position, you need a lot of professional experience."
  },
  {
    "id": 5,
    "german": "das Gehalt",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Gehälter",
    "english": "salary / earnings",
    "pronunciation": "ge-halt",
    "theme": "Arbeit & Beruf",
    "antonym": "der Lohn",
    "example_de": "Sie ist sehr zufrieden, weil ihr Gehalt pünktlich überwiesen wurde.",
    "example_en": "She is very satisfied because her salary was transferred on time."
  },
  {
    "id": 6,
    "german": "der Lebenslauf",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Lebensläufe",
    "english": "CV / resume",
    "pronunciation": "ley-bens-lowf",
    "theme": "Arbeit & Beruf",
    "antonym": "",
    "example_de": "Bitte fügen Sie Ihrer Bewerbung einen aktuellen Lebenslauf bei.",
    "example_en": "Please attach an updated CV to your application."
  },
  {
    "id": 7,
    "german": "die Überweisung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Überweisungen",
    "english": "bank transfer",
    "pronunciation": "ue-ber-vy-zoong",
    "theme": "Banken & Finanzen",
    "antonym": "die Einzahlung",
    "example_de": "Die Überweisung der Miete erfolgt am ersten Tag des Monats.",
    "example_en": "The bank transfer for the rent takes place on the first day of the month."
  },
  {
    "id": 8,
    "german": "das Konto",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Konten",
    "english": "bank account",
    "pronunciation": "kon-toe",
    "theme": "Banken & Finanzen",
    "antonym": "",
    "example_de": "Ich möchte ein neues Konto bei der Sparkasse eröffnen.",
    "example_en": "I would like to open a new bank account at Sparkasse."
  },
  {
    "id": 9,
    "german": "die Gebühr",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Gebühren",
    "english": "fee / charge",
    "pronunciation": "ge-buehr",
    "theme": "Banken & Finanzen",
    "antonym": "kostenlos",
    "example_de": "Für Geldabhebungen an fremden Automaten fällt eine Gebühr an.",
    "example_en": "A fee is charged for withdrawing money from other ATMs."
  },
  {
    "id": 10,
    "german": "der Kredit",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Kredite",
    "english": "credit / bank loan",
    "pronunciation": "krey-deet",
    "theme": "Banken & Finanzen",
    "antonym": "",
    "example_de": "Die Bank hat uns einen Kredit für den Hauskauf bewilligt.",
    "example_en": "The bank has granted us a loan to buy the house."
  },
  {
    "id": 11,
    "german": "die Versicherung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Versicherungen",
    "english": "insurance",
    "pronunciation": "fehr-zich-e-roong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Eine Krankenversicherung ist in Deutschland für jeden gesetzlich Pflicht.",
    "example_en": "Health insurance is legally mandatory for everyone in Germany."
  },
  {
    "id": 12,
    "german": "umweltfreundlich",
    "word_class": "Adjective",
    "gender": "neutral",
    "plural": "",
    "english": "environmentally friendly",
    "pronunciation": "oom-velt-froynt-lich",
    "theme": "Alltag (Adjektive)",
    "antonym": "umweltschädlich",
    "example_de": "Wir sollten umweltfreundliche Produkte kaufen, um die Natur zu schützen.",
    "example_en": "We should buy environmentally friendly products to protect nature."
  },
  {
    "id": 13,
    "german": "die Energie",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Energien",
    "english": "energy / power",
    "pronunciation": "e-ner-gee",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Deutschland investiert stark in erneuerbare Energien.",
    "example_en": "Germany is investing heavily in renewable energies."
  },
  {
    "id": 14,
    "german": "der Umweltschutz",
    "word_class": "Noun",
    "gender": "der",
    "plural": "",
    "english": "environmental protection",
    "pronunciation": "oom-velt-shuts",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Umweltschutz ist ein wichtiges Thema in der heutigen Politik.",
    "example_en": "Environmental protection is an important topic in modern politics."
  },
  {
    "id": 15,
    "german": "die Gesellschaft",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Gesellschaften",
    "english": "society",
    "pronunciation": "ge-zel-shaft",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "In einer multikulturellen Gesellschaft ist gegenseitiger Respekt wichtig.",
    "example_en": "In a multicultural society, mutual respect is important."
  },
  {
    "id": 16,
    "german": "die Regierung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Regierungen",
    "english": "government",
    "pronunciation": "re-gee-roong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Opposition",
    "example_de": "Die Regierung hat neue Maßnahmen zur Bekämpfung der Inflation beschlossen.",
    "example_en": "The government has approved new measures to combat inflation."
  },
  {
    "id": 17,
    "german": "die Steuer",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Steuern",
    "english": "tax",
    "pronunciation": "stoy-ehr",
    "theme": "Banken & Finanzen",
    "antonym": "",
    "example_de": "Auf fast alle Produkte in Deutschland wird die Mehrwertsteuer erhoben.",
    "example_en": "Value-added tax is levied on almost all products in Germany."
  },
  {
    "id": 18,
    "german": "die Wahl",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Wahlen",
    "english": "election / choice",
    "pronunciation": "vahl",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Die Bürger gehen am Sonntag zur Wahl, um ein neues Parlament zu wählen.",
    "example_en": "Citizens go to the polls on Sunday to elect a new parliament."
  },
  {
    "id": 19,
    "german": "entscheiden",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to decide / make a decision",
    "pronunciation": "ent-shy-den",
    "theme": "Alltag (Verben)",
    "antonym": "zögern",
    "example_de": "Ich kann mich nicht entscheiden, welches Auto ich kaufen soll.",
    "example_en": "I cannot make up my mind which car to buy."
  },
  {
    "id": 20,
    "german": "verbessern",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to improve",
    "pronunciation": "fehr-bes-sern",
    "theme": "Alltag (Verben)",
    "antonym": "verschlechtern",
    "example_de": "Er liest viele Bücher, um seine Deutschkenntnisse zu verbessern.",
    "example_en": "He reads many books to improve his knowledge of German."
  },
  {
    "id": 21,
    "german": "die Meinung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Meinungen",
    "english": "opinion",
    "pronunciation": "my-noong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Meiner Meinung nach sollten wir am Wochenende einen Ausflug machen.",
    "example_en": "In my opinion, we should go on an excursion on the weekend."
  },
  {
    "id": 22,
    "german": "der Vorschlag",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Vorschläge",
    "english": "suggestion / proposal",
    "pronunciation": "for-shlahk",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Dein Vorschlag klingt gut, lass uns das so machen.",
    "example_en": "Your suggestion sounds good, let's do it that way."
  },
  {
    "id": 23,
    "german": "abstimmen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to vote / coordinate",
    "pronunciation": "ap-stim-men",
    "theme": "Alltag (Verben)",
    "antonym": "",
    "example_de": "Wir müssen im Team über den nächsten Termin abstimmen.",
    "example_en": "We must vote within the team on the next appointment date."
  },
  {
    "id": 24,
    "german": "sich bewerben",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to apply (for a job)",
    "pronunciation": "be-vair-ben",
    "theme": "Alltag (Verben)",
    "antonym": "kündigen",
    "example_de": "Ich möchte mich um die Stelle im Krankenhaus bewerben.",
    "example_en": "I would like to apply for the position at the hospital."
  },
  {
    "id": 25,
    "german": "teilnehmen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to participate / take part",
    "pronunciation": "tile-nay-men",
    "theme": "Alltag (Verben)",
    "antonym": "absagen",
    "example_de": "Möchten Sie an unserem Deutschkurs im Sommer teilnehmen?",
    "example_en": "Would you like to participate in our German course in summer?"
  },
  {
    "id": 26,
    "german": "der Erfolg",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Erfolge",
    "english": "success",
    "pronunciation": "er-folk",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "der Misserfolg",
    "example_de": "Ich wünsche dir viel Erfolg bei deiner B1-Prüfung!",
    "example_en": "I wish you much success in your B1 exam!"
  },
  {
    "id": 27,
    "german": "die Geduld",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "patience",
    "pronunciation": "ge-doolt",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "die Ungeduld",
    "example_de": "Man braucht viel Geduld, um eine neue Sprache fließend zu lernen.",
    "example_en": "One needs a lot of patience to learn a new language fluently."
  },
  {
    "id": 28,
    "german": "der Zweifel",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Zweifel",
    "english": "doubt",
    "pronunciation": "tsvy-fel",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Gewissheit",
    "example_de": "Es gibt keinen Zweifel daran, dass er den Job bekommen wird.",
    "example_en": "There is no doubt that he will get the job."
  },
  {
    "id": 29,
    "german": "beeinflussen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to influence",
    "pronunciation": "be-yn-floos-sen",
    "theme": "Alltag (Verben)",
    "antonym": "",
    "example_de": "Das Wetter beeinflusst oft meine Stimmung.",
    "example_en": "The weather often influences my mood."
  },
  {
    "id": 30,
    "german": "vergleichen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to compare",
    "pronunciation": "fehr-gly-chen",
    "theme": "Alltag (Verben)",
    "antonym": "",
    "example_de": "Wir sollten verschiedene Angebote vergleichen, bevor wir buchen.",
    "example_en": "We should compare different offers before we book."
  },
  {
    "id": 31,
    "german": "der Unterschied",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Unterschiede",
    "english": "difference",
    "pronunciation": "oon-ter-sheet",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Ähnlichkeit",
    "example_de": "Was ist der Unterschied zwischen diesen beiden Wörtern?",
    "example_en": "What is the difference between these two words?"
  },
  {
    "id": 32,
    "german": "die Beziehung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Beziehungen",
    "english": "relationship / connection",
    "pronunciation": "be-tsee-oong",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Die beiden Länder haben gute wirtschaftliche Beziehungen.",
    "example_en": "The two countries have good economic relations."
  },
  {
    "id": 33,
    "german": "die Wahrheit",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Wahrheiten",
    "english": "truth",
    "pronunciation": "vahr-hyt",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Lüge",
    "example_de": "Sag mir bitte die Wahrheit, auch wenn sie schwierig ist.",
    "example_en": "Please tell me the truth, even if it is difficult."
  },
  {
    "id": 34,
    "german": "die Zukunft",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "future",
    "pronunciation": "tsoo-koonft",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Vergangenheit",
    "example_de": "Niemand weiß genau, was in der Zukunft passieren wird.",
    "example_en": "Nobody knows exactly what will happen in the future."
  },
  {
    "id": 35,
    "german": "versprechen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to promise",
    "pronunciation": "fehr-shprech-en",
    "theme": "Alltag (Verben)",
    "antonym": "",
    "example_de": "Er hat versprochen, mir bei der Vorbereitung zu helfen.",
    "example_en": "He promised to help me with the preparation."
  },
  {
    "id": 36,
    "german": "erklären",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english": "to explain",
    "pronunciation": "er-klair-en",
    "theme": "Alltag (Verben)",
    "antonym": "",
    "example_de": "Können Sie mir bitte die Bedeutung dieses Wortes erklären?",
    "example_en": "Could you please explain the meaning of this word to me?"
  },
  {
    "id": 37,
    "german": "die Lösung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Lösungen",
    "english": "solution / answer",
    "pronunciation": "loe-zoong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "das Problem",
    "example_de": "Wir müssen eine schnelle Lösung für dieses technische Problem finden.",
    "example_en": "We must find a quick solution for this technical problem."
  },
  {
    "id": 38,
    "german": "die Prüfung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Prüfungen",
    "english": "exam / test",
    "pronunciation": "proo-foong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Die mündliche Prüfung dauert ungefähr fünfzehn Minuten.",
    "example_en": "The oral exam lasts approximately fifteen minutes."
  },
  {
    "id": 39,
    "german": "das Ergebnis",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Ergebnisse",
    "english": "result / outcome",
    "pronunciation": "er-gep-nis",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Die Ergebnisse der schriftlichen Prüfung hängen am schwarzen Brett.",
    "example_en": "The results of the written exam are posted on the bulletin board."
  },
  {
    "id": 40,
    "german": "die Voraussetzung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Voraussetzungen",
    "english": "requirement / prerequisite",
    "pronunciation": "fo-row-set-soong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Ein B1-Zertifikat ist eine wichtige Voraussetzung für das Visum.",
    "example_en": "A B1 certificate is an important requirement for the visa."
  },
  {
    "id": 41,
    "german": "die Vereinbarung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Vereinbarungen",
    "english": "agreement / arrangement",
    "pronunciation": "fehr-yn-bah-roong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Wir haben eine Vereinbarung über die wöchentlichen Arbeitszeiten getroffen.",
    "example_en": "We have reached an agreement on the weekly working hours."
  },
  {
    "id": 42,
    "german": "die Verbindung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Verbindungen",
    "english": "connection / contact",
    "pronunciation": "fehr-bin-doong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Trennung",
    "example_de": "Die Internetverbindung ist heute leider sehr langsam.",
    "example_en": "The internet connection is unfortunately very slow today."
  },
  {
    "id": 43,
    "german": "das Gerät",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Geräte",
    "english": "device / appliance",
    "pronunciation": "ge-raet",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Schalten Sie bitte alle elektronischen Geräte während des Flugs aus.",
    "example_en": "Please turn off all electronic devices during the flight."
  },
  {
    "id": 44,
    "german": "die Werbung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Werbungen",
    "english": "advertising / commercial",
    "pronunciation": "vair-boong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Im Fernsehen gibt es zu viel Werbung, das nervt mich.",
    "example_en": "There is too much advertising on television; it annoys me."
  },
  {
    "id": 45,
    "german": "die Nachfrage",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Nachfragen",
    "english": "demand / inquiry",
    "pronunciation": "nahch-frah-guh",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "das Angebot",
    "example_de": "Die Nachfrage nach Elektroautos ist im letzten Jahr gestiegen.",
    "example_en": "The demand for electric cars has increased over the last year."
  },
  {
    "id": 46,
    "german": "das Angebot",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Angebote",
    "english": "offer / deal",
    "pronunciation": "ahn-ge-boht",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "die Nachfrage",
    "example_de": "Dieses Sonderangebot im Supermarkt gilt nur bis Samstag.",
    "example_en": "This special offer in the supermarket is only valid until Saturday."
  },
  {
    "id": 47,
    "german": "die Wirtschaft",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Wirtschaften",
    "english": "economy",
    "pronunciation": "virt-shaft",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Die globale Wirtschaft erholt sich langsam nach der Krise.",
    "example_en": "The global economy is slowly recovering after the crisis."
  },
  {
    "id": 48,
    "german": "der Vertrag",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Verträge",
    "english": "contract / agreement",
    "pronunciation": "fehr-trahk",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Bevor Sie unterschreiben, sollten Sie den Vertrag genau lesen.",
    "example_en": "Before you sign, you should read the contract carefully."
  },
  {
    "id": 49,
    "german": "die Kündigung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Kündigungen",
    "english": "termination / resignation notice",
    "pronunciation": "kuen-di-goong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Einstellung",
    "example_de": "Er hat gestern seine schriftliche Kündigung eingereicht.",
    "example_en": "He submitted his written resignation notice yesterday."
  },
  {
    "id": 50,
    "german": "der Ausweis",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Ausweise",
    "english": "identity card / ID",
    "pronunciation": "ows-vys",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Ohne gültigen Ausweis darf man die Grenze nicht passieren.",
    "example_en": "Without a valid ID, one is not allowed to cross the border."
  },
  {
    "id": 51,
    "german": "die Anmeldung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Anmeldungen",
    "english": "registration",
    "pronunciation": "ahn-mel-doong",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "die Abmeldung",
    "example_de": "Die Anmeldung zum Sprachkurs erfolgt online auf unserer Website.",
    "example_en": "The registration for the language course takes place online on our website."
  },
  {
    "id": 52,
    "german": "die Behörde",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Behörden",
    "english": "authority / official agency",
    "pronunciation": "be-hoer-de",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Für die Arbeitserlaubnis müssen wir zu einer deutschen Behörde gehen.",
    "example_en": "For the work permit, we must go to a German authority."
  },
  {
    "id": 53,
    "german": "das Dokument",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Dokumente",
    "english": "document",
    "pronunciation": "do-koo-ment",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Bringen Sie bitte alle erforderlichen Dokumente zur Anmeldung mit.",
    "example_en": "Please bring all required documents with you to the registration."
  },
  {
    "id": 54,
    "german": "der Empfänger",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Empfänger",
    "english": "recipient / addressee",
    "pronunciation": "emp-fengk-er",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "der Sender",
    "example_de": "Der Name des Empfängers steht unten rechts auf dem Briefumschlag.",
    "example_en": "The recipient's name is on the bottom right of the envelope."
  },
  {
    "id": 55,
    "german": "die Absicht",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Absichten",
    "english": "intention / purpose",
    "pronunciation": "ap-zicht",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Es war nicht meine Absicht, dich zu verletzen, es tut mir leid.",
    "example_en": "It was not my intention to hurt you, I am sorry."
  },
  {
    "id": 56,
    "german": "das Abenteuer",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Abenteuer",
    "english": "adventure",
    "pronunciation": "ah-ben-toy-er",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Unsere Rucksackreise durch Asien war ein großes Abenteuer.",
    "example_en": "Our backpacking trip through Asia was a great adventure."
  },
  {
    "id": 57,
    "german": "die Abfahrt",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Abfahrten",
    "english": "departure",
    "pronunciation": "ap-fahrt",
    "theme": "Reisen & Mobilität",
    "antonym": "die Ankunft",
    "example_de": "Die Abfahrt des Zuges ist für genau 14:32 Uhr geplant.",
    "example_en": "The departure of the train is scheduled for exactly 2:32 p.m."
  },
  {
    "id": 58,
    "german": "die Ankunft",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Ankünfte",
    "english": "arrival",
    "pronunciation": "ahn-koonft",
    "theme": "Reisen & Mobilität",
    "antonym": "die Abfahrt",
    "example_de": "Nach der Ankunft am Flughafen müssen wir unser Gepäck abholen.",
    "example_en": "After the arrival at the airport, we have to pick up our luggage."
  },
  {
    "id": 59,
    "german": "der Anschluss",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Anschlüsse",
    "english": "connecting train / connection",
    "pronunciation": "ahn-shloos",
    "theme": "Reisen & Mobilität",
    "antonym": "",
    "example_de": "Der Zug hat Verspätung, wir werden unseren Anschluss in Köln verpassen.",
    "example_en": "The train is delayed; we will miss our connection in Cologne."
  },
  {
    "id": 60,
    "german": "der Aufenthalt",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Aufenthalte",
    "english": "stay / stopover",
    "pronunciation": "owf-ent-halt",
    "theme": "Reisen & Mobilität",
    "antonym": "",
    "example_de": "Wir wünschen Ihnen einen angenehmen Aufenthalt in unserem Hotel.",
    "example_en": "We wish you a pleasant stay in our hotel."
  },
  {
    "id": 61,
    "german": "die Verspätung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Verspätungen",
    "english": "delay",
    "pronunciation": "fehr-shpae-toong",
    "theme": "Reisen & Mobilität",
    "antonym": "die Pünktlichkeit",
    "example_de": "Der ICE hat heute leider eine Verspätung von zwanzig Minuten.",
    "example_en": "The ICE unfortunately has a delay of twenty minutes today."
  },
  {
    "id": 62,
    "german": "die Beschwerde",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Beschwerden",
    "english": "complaint",
    "pronunciation": "be-shvair-de",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Der Hotelgast hat eine Beschwerde über den schlechten Service eingereicht.",
    "example_en": "The hotel guest has submitted a complaint about the poor service."
  },
  {
    "id": 63,
    "german": "die Empfehlung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Empfehlungen",
    "english": "recommendation",
    "pronunciation": "emp-fay-loong",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Vielen Dank für Ihre Empfehlung, das Restaurant war wirklich hervorragend.",
    "example_en": "Thank you very much for your recommendation; the restaurant was indeed outstanding."
  },
  {
    "id": 64,
    "german": "die Beratung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Beratungen",
    "english": "consultation / counseling",
    "pronunciation": "be-rah-toong",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "",
    "example_de": "Die Agentur bietet eine kostenlose Beratung für Unternehmensgründer an.",
    "example_en": "The agency offers free consulting for business founders."
  },
  {
    "id": 65,
    "german": "die Unterstützung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Unterstützungen",
    "english": "assistance / support",
    "pronunciation": "oon-ter-stuet-soong",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "",
    "example_de": "Wir danken Ihnen herzlich für Ihre finanzielle Unterstützung.",
    "example_en": "We thank you cordially for your financial support."
  },
  {
    "id": 66,
    "german": "die Erlaubnis",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Erlaubnisse",
    "english": "permission / permit",
    "pronunciation": "er-lowp-nis",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "das Verbot",
    "example_de": "Haben Sie eine Erlaubnis, in diesem Park zu grillen?",
    "example_en": "Do you have permission to grill in this park?"
  },
  {
    "id": 67,
    "german": "das Verbot",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Verbote",
    "english": "prohibition / ban",
    "pronunciation": "fehr-boht",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Erlaubnis",
    "example_de": "In diesem Gebäude gilt ein absolutes Rauchverbot.",
    "example_en": "An absolute smoking ban applies in this building."
  },
  {
    "id": 68,
    "german": "die Sicherheit",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Sicherheiten",
    "english": "safety / security",
    "pronunciation": "zich-er-hyt",
    "theme": "Alltag (Nomen: L-Z)",
    "antonym": "die Gefahr",
    "example_de": "Die Sicherheit unserer Mitarbeiter hat oberste Priorität.",
    "example_en": "The safety of our employees is the top priority."
  },
  {
    "id": 69,
    "german": "die Gefahr",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Gefahren",
    "english": "danger / risk",
    "pronunciation": "ge-fahr",
    "theme": "Alltag (Nomen: A-K)",
    "antonym": "die Sicherheit",
    "example_de": "Rauchen ist eine große Gefahr für die Gesundheit.",
    "example_en": "Smoking is a great danger to health."
  },
  {
    "id": 70,
    "german": "vorsichtig",
    "word_class": "Adjective",
    "gender": "neutral",
    "plural": "",
    "english": "cautious / careful",
    "pronunciation": "for-zich-tich",
    "theme": "Alltag (Adjektive)",
    "antonym": "unvorsichtig",
    "example_de": "Sei vorsichtig, die Straße ist heute extrem glatt und rutschig.",
    "example_en": "Be careful; the road is extremely slippery today."
  },
  {
    "id": 71,
    "german": "die Gesundheit",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "health",
    "pronunciation": "ge-zoont-hyt",
    "theme": "Gesundheit & Körper",
    "antonym": "die Krankheit",
    "example_de": "Ich trinke viel Wasser, weil das gut für die Gesundheit ist.",
    "example_en": "I drink a lot of water because it is good for the health."
  },
  {
    "id": 72,
    "german": "die Untersuchung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Untersuchungen",
    "english": "medical examination",
    "pronunciation": "oon-ter-zoo-choong",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Die jährliche Untersuchung beim Zahnarzt ist sehr wichtig.",
    "example_en": "The annual examination at the dentist is very important."
  },
  {
    "id": 73,
    "german": "die Verletzung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Verletzungen",
    "english": "injury",
    "pronunciation": "fehr-let-soong",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Die Verletzung am Fuß heilt glücklicherweise sehr schnell.",
    "example_en": "The injury on the foot is fortunately healing very quickly."
  },
  {
    "id": 74,
    "german": "das Medikament",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Medikamente",
    "english": "medication / medicine",
    "pronunciation": "me-dee-kah-ment",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Der Arzt hat mir ein starkes Medikament gegen die Schmerzen verschrieben.",
    "example_en": "The doctor prescribed me a strong medication for the pain."
  },
  {
    "id": 75,
    "german": "die Apotheke",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Apotheken",
    "english": "pharmacy / drugstore",
    "pronunciation": "ah-po-tay-ke",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Ich muss zur Apotheke gehen, um dieses Rezept einzulösen.",
    "example_en": "I have to go to the pharmacy to redeem this prescription."
  },
  {
    "id": 76,
    "german": "die Schmerzen",
    "word_class": "Noun",
    "gender": "neutral",
    "plural": "Schmerzen",
    "english": "pains / aches",
    "pronunciation": "shmairt-sen",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Haben Sie noch Schmerzen im Rücken oder ist es schon besser?",
    "example_en": "Are you still in pain in your back, or is it already better?"
  },
  {
    "id": 77,
    "german": "die Besserung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "recovery / improvement",
    "pronunciation": "bes-se-roong",
    "theme": "Gesundheit & Körper",
    "antonym": "die Verschlechterung",
    "example_de": "Gute Besserung! Hoffentlich bist du bald wieder gesund.",
    "example_en": "Get well soon! Hopefully you will be healthy again soon."
  },
  {
    "id": 78,
    "german": "der Unfall",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Unfälle",
    "english": "accident",
    "pronunciation": "oon-fal",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Es gab einen kleinen Unfall auf der Autobahn, aber niemand wurde verletzt.",
    "example_en": "There was a small accident on the highway, but nobody was injured."
  },
  {
    "id": 79,
    "german": "der Patient",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Patienten",
    "english": "patient (male)",
    "pronunciation": "pah-tsee-ent",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Der Arzt spricht gerade aufmerksam mit dem neuen Patienten.",
    "example_en": "The doctor is currently speaking attentively with the new patient."
  },
  {
    "id": 80,
    "german": "die Patientin",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Patientinnen",
    "english": "patient (female)",
    "pronunciation": "pah-tsee-en-tin",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Die Patientin wartet schon seit einer halben Stunde im Wartezimmer.",
    "example_en": "The patient has been waiting in the waiting room for half an hour."
  },
  {
    "id": 81,
    "german": "die Ernährung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "nutrition / diet",
    "pronunciation": "er-nae-roong",
    "theme": "Gesundheit & Körper",
    "antonym": "",
    "example_de": "Eine gesunde Ernährung mit viel Gemüse ist wichtig für den Körper.",
    "example_en": "A healthy diet with lots of vegetables is important for the body."
  },
  {
    "id": 82,
    "german": "die Bewegung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Bewegungen",
    "english": "movement / physical exercise",
    "pronunciation": "be-vay-goong",
    "theme": "Gesundheit & Körper",
    "antonym": "die Ruhe",
    "example_de": "Ausreichende Bewegung an der frischen Luft stärkt das Immunsystem.",
    "example_en": "Sufficient exercise in the fresh air strengthens the immune system."
  },
  {
    "id": 83,
    "german": "das Klima",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Klimate",
    "english": "climate",
    "pronunciation": "klee-mah",
    "theme": "Wetter",
    "antonym": "",
    "example_de": "Der Klimawandel verändert das globale Wetter und schadet der Umwelt.",
    "example_en": "Climate change alters global weather and harms the environment."
  },
  {
    "id": 84,
    "german": "die Umwelt",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "environment",
    "pronunciation": "oom-velt",
    "theme": "Wetter",
    "antonym": "",
    "example_de": "Wir müssen Plastikmüll vermeiden, um unsere Umwelt zu schonen.",
    "example_en": "We must avoid plastic waste in order to protect our environment."
  },
  {
    "id": 85,
    "german": "die Landschaft",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Landschaften",
    "english": "landscape / scenery",
    "pronunciation": "lant-shaft",
    "theme": "Wetter",
    "antonym": "",
    "example_de": "Die bergige Landschaft in Süddeutschland ist im Winter wunderschön.",
    "example_en": "The mountainous landscape in Southern Germany is beautiful in winter."
  },
  {
    "id": 86,
    "german": "die Jahreszeit",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Jahreszeiten",
    "english": "season",
    "pronunciation": "yah-res-tsyt",
    "theme": "Wetter",
    "antonym": "",
    "example_de": "Der Frühling ist meine absolute Lieblings-Jahreszeit, weil alles blüht.",
    "example_en": "Spring is my absolute favorite season because everything blooms."
  },
  {
    "id": 87,
    "german": "der Umweltschutz",
    "word_class": "Noun",
    "gender": "der",
    "plural": "",
    "english": "environmental protection",
    "pronunciation": "oom-velt-shuts",
    "theme": "Wetter",
    "antonym": "",
    "example_de": "Jeder Bürger kann im Alltag einen kleinen Beitrag zum Umweltschutz leisten.",
    "example_en": "Every citizen can make a small contribution to environmental protection in daily life."
  },
  {
    "id": 88,
    "german": "die Verpackung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Verpackungen",
    "english": "packaging",
    "pronunciation": "fehr-pak-oong",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Bitte wirf die Verpackung aus Plastik in die gelbe Tonne.",
    "example_en": "Please throw the plastic packaging into the yellow bin."
  },
  {
    "id": 89,
    "german": "der Rabatt",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Rabatte",
    "english": "discount",
    "pronunciation": "rah-bat",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Auf diesen Wintermantel bekommen Sie heute zehn Prozent Rabatt.",
    "example_en": "You get a ten percent discount on this winter coat today."
  },
  {
    "id": 90,
    "german": "die Quittung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Quittungen",
    "english": "receipt / proof of payment",
    "pronunciation": "kvit-oong",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Heben Sie die Quittung auf, falls Sie das Produkt umtauschen möchten.",
    "example_en": "Keep the receipt in case you would like to exchange the product."
  },
  {
    "id": 91,
    "german": "der Kassenzettel",
    "word_class": "Noun",
    "gender": "der",
    "plural": "Kassenzettel",
    "english": "receipt / cash register slip",
    "pronunciation": "kas-sen-tset-tel",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Ich habe den Kassenzettel verloren und kann das Hemd nicht mehr zurückgeben.",
    "example_en": "I lost the sales receipt and cannot return the shirt anymore."
  },
  {
    "id": 92,
    "german": "die Garantie",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Garantien",
    "english": "warranty / guarantee",
    "pronunciation": "gah-rahn-tee",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Der Fernseher hat eine Garantie von vier Jahren ab Kaufdatum.",
    "example_en": "The television has a warranty of four years from the date of purchase."
  },
  {
    "id": 93,
    "german": "günstig",
    "word_class": "Adjective",
    "gender": "neutral",
    "plural": "",
    "english": "cheap / low-priced / favorable",
    "pronunciation": "guen-stich",
    "theme": "Alltag (Adjektive)",
    "antonym": "teuer",
    "example_de": "In diesem Geschäft gibt es sehr günstige Kleidung zu kaufen.",
    "example_en": "In this shop, you can buy very cheap clothes."
  },
  {
    "id": 94,
    "german": "kostenlos",
    "word_class": "Adjective",
    "gender": "neutral",
    "plural": "",
    "english": "free of charge",
    "pronunciation": "kos-ten-lohs",
    "theme": "Alltag (Adjektive)",
    "antonym": "kostenpflichtig",
    "example_de": "Der Versand der Ware ist ab fünfzig Euro Warenwert kostenlos.",
    "example_en": "The shipping of the goods is free of charge from a purchase value of fifty euros."
  },
  {
    "id": 95,
    "german": "die Auswahl",
    "word_class": "Noun",
    "gender": "die",
    "plural": "",
    "english": "selection / choice",
    "pronunciation": "ows-vahl",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Dieses Kaufhaus hat eine riesige Auswahl an Schuhen.",
    "example_en": "This department store has a huge selection of shoes."
  },
  {
    "id": 96,
    "german": "die Mode",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Moden",
    "english": "fashion / style",
    "pronunciation": "moh-de",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Sie interessiert sich sehr für französische Mode und Zeitschriften.",
    "example_en": "She is very interested in French fashion and magazines."
  },
  {
    "id": 97,
    "german": "die Qualität",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Qualitäten",
    "english": "quality",
    "pronunciation": "kvah-lee-taet",
    "theme": "Einkaufen & Konsum",
    "antonym": "die Minderwertigkeit",
    "example_de": "Die Qualität dieser Bio-Lebensmittel rechtfertigt den höheren Preis.",
    "example_en": "The quality of these organic foods justifies the higher price."
  },
  {
    "id": 98,
    "german": "die Wirtschaft",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Wirtschaften",
    "english": "economy / hospitality",
    "pronunciation": "virt-shaft",
    "theme": "Einkaufen & Konsum",
    "antonym": "",
    "example_de": "Die bayerische Wirtschaft wächst dank des starken Tourismus.",
    "example_en": "The Bavarian economy is growing thanks to strong tourism."
  },
  {
    "id": 99,
    "german": "die Werbung",
    "word_class": "Noun",
    "gender": "die",
    "plural": "Werbungen",
    "english": "advertisement / marketing",
    "pronunciation": "vair-boong",
    "theme": "Medien & Technologie",
    "antonym": "",
    "example_de": "Durch gezielte Werbung im Internet konnte die Firma mehr Kunden gewinnen.",
    "example_en": "Through targeted advertising on the internet, the company was able to attract more customers."
  },
  {
    "id": 100,
    "german": "das Netz",
    "word_class": "Noun",
    "gender": "das",
    "plural": "Netze",
    "english": "network / web / grid",
    "pronunciation": "nets",
    "theme": "Medien & Technologie",
    "antonym": "",
    "example_de": "In diesem kleinen Dorf mitten im Wald hat man leider kein Mobilfunknetz.",
    "example_en": "In this small village in the middle of the forest, there is unfortunately no mobile network."
  }
]

# Write database to b1/wordlist.json
with open(TARGET_FILE, "w", encoding="utf-8") as f:
    json.dump(b1_words, f, indent=2, ensure_ascii=False)

print(f"SUCCESS: Generated Level B1 wordlist in {TARGET_FILE} with {len(b1_words)} items.")
