import os
import json

# Absolute path to save the level A1 wordlist
TARGET_DIR = r"d:\Aman\_________Projects\A1-B1_German\a1"
TARGET_FILE = os.path.join(TARGET_DIR, "wordlist.json")

os.makedirs(TARGET_DIR, exist_ok=True)

# Sourced & validated Goethe-Institut A1 standard vocabulary database
a1_words = [
  # --- ALLTAG NOMEN: A-K ---
  {
    "word": "der Abend",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-e",
    "english_translation": "evening",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Guten Abend! Wie geht es Ihnen?",
    "example_sentence_en": "Good evening! How are you?",
    "antonym": "der Morgen",
    "pronunciation_hint": "ah-bent"
  },
  {
    "word": "die Adresse",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "address",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Wie ist Ihre Adresse?",
    "example_sentence_en": "What is your address?",
    "antonym": "",
    "pronunciation_hint": "ah-dres-uh"
  },
  {
    "word": "der Apfel",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "¨-",
    "english_translation": "apple",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Ich esse einen Apfel.",
    "example_sentence_en": "I am eating an apple.",
    "antonym": "",
    "pronunciation_hint": "ap-fel"
  },
  {
    "word": "das Baby",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-s",
    "english_translation": "baby",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Das Baby schläft.",
    "example_sentence_en": "The baby is sleeping.",
    "antonym": "",
    "pronunciation_hint": "bay-bee"
  },
  {
    "word": "das Bett",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-en",
    "english_translation": "bed",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Das Bett ist sehr bequem.",
    "example_sentence_en": "The bed is very comfortable.",
    "antonym": "",
    "pronunciation_hint": "bet"
  },
  {
    "word": "das Bild",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-er",
    "english_translation": "picture / picture frame",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Das Bild an der Wand ist schön.",
    "example_sentence_en": "The picture on the wall is beautiful.",
    "antonym": "",
    "pronunciation_hint": "bilt"
  },
  {
    "word": "das Buch",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "¨-er",
    "english_translation": "book",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Ich lese ein Buch.",
    "example_sentence_en": "I am reading a book.",
    "antonym": "",
    "pronunciation_hint": "bukh"
  },
  {
    "word": "der Computer",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-",
    "english_translation": "computer",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Mein Computer ist neu.",
    "example_sentence_en": "My computer is new.",
    "antonym": "",
    "pronunciation_hint": "kom-pyoo-ter"
  },
  {
    "word": "das Ding",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-e",
    "english_translation": "thing / object",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Was ist das für ein Ding?",
    "example_sentence_en": "What kind of thing is that?",
    "antonym": "",
    "pronunciation_hint": "ding"
  },
  {
    "word": "die Eltern",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "(Pl.)",
    "english_translation": "parents",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Meine Eltern leben in Spanien.",
    "example_sentence_en": "My parents live in Spain.",
    "antonym": "die Kinder",
    "pronunciation_hint": "el-tern"
  },
  {
    "word": "die Familie",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "family",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Ich liebe meine Familie.",
    "example_sentence_en": "I love my family.",
    "antonym": "",
    "pronunciation_hint": "fah-mee-lee-uh"
  },
  {
    "word": "die Flasche",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "bottle",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Eine Flasche Wasser, bitte.",
    "example_sentence_en": "A bottle of water, please.",
    "antonym": "",
    "pronunciation_hint": "flash-uh"
  },
  {
    "word": "die Frage",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "question",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Ich habe eine Frage.",
    "example_sentence_en": "I have a question.",
    "antonym": "die Antwort",
    "pronunciation_hint": "frah-guh"
  },
  {
    "word": "der Freund",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-e",
    "english_translation": "male friend",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Das ist mein Freund Thomas.",
    "example_sentence_en": "This is my friend Thomas.",
    "antonym": "der Feind",
    "pronunciation_hint": "froynt"
  },
  {
    "word": "die Freundin",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-nen",
    "english_translation": "female friend",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Das ist meine Freundin Julia.",
    "example_sentence_en": "This is my friend Julia.",
    "antonym": "",
    "pronunciation_hint": "froyn-din"
  },
  {
    "word": "das Haus",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "¨-er",
    "english_translation": "house",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Unser Haus ist sehr groß.",
    "example_sentence_en": "Our house is very big.",
    "antonym": "",
    "pronunciation_hint": "hows"
  },
  {
    "word": "das Kind",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-er",
    "english_translation": "child",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "Das Kind spielt im Garten.",
    "example_sentence_en": "The child is playing in the garden.",
    "antonym": "die Eltern",
    "pronunciation_hint": "kint"
  },
  {
    "word": "die Küche",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "kitchen",
    "category": "Alltag (Nomen: A-K)",
    "example_sentence_de": "In der Küche kochen wir.",
    "example_sentence_en": "In the kitchen we cook.",
    "antonym": "",
    "pronunciation_hint": "kue-chuh"
  },

  # --- ALLTAG NOMEN: L-Z ---
  {
    "word": "der Mann",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "¨-er",
    "english_translation": "man / husband",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Mein Mann arbeitet bei Siemens.",
    "example_sentence_en": "My husband works at Siemens.",
    "antonym": "die Frau",
    "pronunciation_hint": "man"
  },
  {
    "word": "der Morgen",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-",
    "english_translation": "morning",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Guten Morgen, allerseits!",
    "example_sentence_en": "Good morning, everyone!",
    "antonym": "der Abend",
    "pronunciation_hint": "mor-gen"
  },
  {
    "word": "der Name",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-n",
    "english_translation": "name",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Mein Name ist Hans.",
    "example_sentence_en": "My name is Hans.",
    "antonym": "",
    "pronunciation_hint": "nah-muh"
  },
  {
    "word": "die Person",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-en",
    "english_translation": "person",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Wie viele Personen sind Sie?",
    "example_sentence_en": "How many people are there in your group?",
    "antonym": "",
    "pronunciation_hint": "pehr-zohn"
  },
  {
    "word": "die Schule",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "school",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Das Kind geht zur Schule.",
    "example_sentence_en": "The child goes to school.",
    "antonym": "",
    "pronunciation_hint": "shool-uh"
  },
  {
    "word": "die Tasche",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "bag / pocket",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Ist das deine Tasche?",
    "example_sentence_en": "Is that your bag?",
    "antonym": "",
    "pronunciation_hint": "tash-uh"
  },
  {
    "word": "der Tisch",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-e",
    "english_translation": "table",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Das Essen steht auf dem Tisch.",
    "example_sentence_en": "The food is on the table.",
    "antonym": "",
    "pronunciation_hint": "tish"
  },
  {
    "word": "die Uhr",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-en",
    "english_translation": "clock / watch / hour",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Wie viel Uhr ist es?",
    "example_sentence_en": "What time is it?",
    "antonym": "",
    "pronunciation_hint": "oor"
  },
  {
    "word": "der Vater",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "¨",
    "english_translation": "father",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Mein Vater ist Lehrer.",
    "example_sentence_en": "My father is a teacher.",
    "antonym": "die Mutter",
    "pronunciation_hint": "fah-tehr"
  },
  {
    "word": "die Woche",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-n",
    "english_translation": "week",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Die Woche hat sieben Tage.",
    "example_sentence_en": "The week has seven days.",
    "antonym": "",
    "pronunciation_hint": "vokh-uh"
  },
  {
    "word": "die Wohnung",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-en",
    "english_translation": "apartment / flat",
    "category": "Alltag (Nomen: L-Z)",
    "example_sentence_de": "Unsere Wohnung hat drei Zimmer.",
    "example_sentence_en": "Our apartment has three rooms.",
    "antonym": "",
    "pronunciation_hint": "vohn-oong"
  },

  # --- ALLTAG VERBEN ---
  {
    "word": "arbeiten",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to work",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich arbeite bei einer Bank.",
    "example_sentence_en": "I work at a bank.",
    "antonym": "ausruhen",
    "pronunciation_hint": "ahr-by-ten"
  },
  {
    "word": "essen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to eat",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Wir essen Pizza.",
    "example_sentence_en": "We are eating pizza.",
    "antonym": "",
    "pronunciation_hint": "es-sen"
  },
  {
    "word": "fahren",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to drive / ride / travel",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich fahre mit der U-Bahn.",
    "example_sentence_en": "I am riding the subway.",
    "antonym": "",
    "pronunciation_hint": "fah-ren"
  },
  {
    "word": "fragen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to ask",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Darf ich Sie etwas fragen?",
    "example_sentence_en": "May I ask you something?",
    "antonym": "antworten",
    "pronunciation_hint": "frah-gen"
  },
  {
    "word": "gehen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to go / walk",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich gehe jetzt nach Hause.",
    "example_sentence_en": "I am going home now.",
    "antonym": "stehen",
    "pronunciation_hint": "gay-en"
  },
  {
    "word": "haben",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to have",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich habe ein kleines Auto.",
    "example_sentence_en": "I have a small car.",
    "antonym": "",
    "pronunciation_hint": "hah-ben"
  },
  {
    "word": "heißen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to be called / named",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich heiße Michael.",
    "example_sentence_en": "My name is Michael.",
    "antonym": "",
    "pronunciation_hint": "hy-ssen"
  },
  {
    "word": "hören",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to hear / listen",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich höre gern Musik.",
    "example_sentence_en": "I like listening to music.",
    "antonym": "",
    "pronunciation_hint": "hoe-ren"
  },
  {
    "word": "kaufen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to buy",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich kaufe im Supermarkt ein.",
    "example_sentence_en": "I buy things in the supermarket.",
    "antonym": "verkaufen",
    "pronunciation_hint": "kow-fen"
  },
  {
    "word": "kommen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to come",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich komme aus Deutschland.",
    "example_sentence_en": "I come from Germany.",
    "antonym": "gehen",
    "pronunciation_hint": "kom-men"
  },
  {
    "word": "lernen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to learn / study",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich lerne Deutsch bei der Volkshochschule.",
    "example_sentence_en": "I am learning German at the adult education center.",
    "antonym": "lehren",
    "pronunciation_hint": "lehr-nen"
  },
  {
    "word": "lesen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to read",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich lese die Zeitung.",
    "example_sentence_en": "I am reading the newspaper.",
    "antonym": "",
    "pronunciation_hint": "lay-zen"
  },
  {
    "word": "machen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to make / do",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Was machst du am Wochenende?",
    "example_sentence_en": "What are you doing on the weekend?",
    "antonym": "",
    "pronunciation_hint": "makh-en"
  },
  {
    "word": "schreiben",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to write",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich schreibe eine E-Mail.",
    "example_sentence_en": "I am writing an email.",
    "antonym": "",
    "pronunciation_hint": "shry-ben"
  },
  {
    "word": "sehen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to see / watch",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich sehe einen Film.",
    "example_sentence_en": "I am watching a movie.",
    "antonym": "",
    "pronunciation_hint": "zay-en"
  },
  {
    "word": "spielen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to play",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Wir spielen Fußball.",
    "example_sentence_en": "We are playing soccer.",
    "antonym": "",
    "pronunciation_hint": "shpee-len"
  },
  {
    "word": "sprechen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to speak",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Sprechen Sie Englisch?",
    "example_sentence_en": "Do you speak English?",
    "antonym": "",
    "pronunciation_hint": "shprech-en"
  },
  {
    "word": "trinken",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to drink",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich trinke ein Glas Wasser.",
    "example_sentence_en": "I drink a glass of water.",
    "antonym": "",
    "pronunciation_hint": "trink-en"
  },
  {
    "word": "verstehen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to understand",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich verstehe das Wort nicht.",
    "example_sentence_en": "I do not understand the word.",
    "antonym": "missverstehen",
    "pronunciation_hint": "fehr-shtay-en"
  },
  {
    "word": "wohnen",
    "word_class": "Verb",
    "gender": "neutral",
    "plural": "",
    "english_translation": "to live / reside",
    "category": "Alltag (Verben)",
    "example_sentence_de": "Ich wohne in Berlin.",
    "example_sentence_en": "I live in Berlin.",
    "antonym": "",
    "pronunciation_hint": "vohn-en"
  },

  # --- ALLTAG ADJEKTIVE ---
  {
    "word": "alt",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "old",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Mein Auto ist sehr alt.",
    "example_sentence_en": "My car is very old.",
    "antonym": "neu / jung",
    "pronunciation_hint": "alt"
  },
  {
    "word": "billig",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "cheap",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Das Brot ist sehr billig.",
    "example_sentence_en": "The bread is very cheap.",
    "antonym": "teuer",
    "pronunciation_hint": "bil-lik"
  },
  {
    "word": "groß",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "big / large / tall",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Die Wohnung ist groß.",
    "example_sentence_en": "The apartment is large.",
    "antonym": "klein",
    "pronunciation_hint": "grohs"
  },
  {
    "word": "gut",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "good",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Das Essen schmeckt sehr gut.",
    "example_sentence_en": "The food tastes very good.",
    "antonym": "schlecht",
    "pronunciation_hint": "goot"
  },
  {
    "word": "heiß",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "hot",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Der Tee ist sehr heiß.",
    "example_sentence_en": "The tea is very hot.",
    "antonym": "kalt",
    "pronunciation_hint": "hice"
  },
  {
    "word": "jung",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "young",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Sie ist eine junge Frau.",
    "example_sentence_en": "She is a young woman.",
    "antonym": "alt",
    "pronunciation_hint": "yoong"
  },
  {
    "word": "kalt",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "cold",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Im Winter ist es kalt.",
    "example_sentence_en": "In winter it is cold.",
    "antonym": "heiß / warm",
    "pronunciation_hint": "kalt"
  },
  {
    "word": "klein",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "small / little",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Das Zimmer ist ein bisschen klein.",
    "example_sentence_en": "The room is a bit small.",
    "antonym": "groß",
    "pronunciation_hint": "klyne"
  },
  {
    "word": "lang",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "long",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Der Weg zum Bahnhof ist lang.",
    "example_sentence_en": "The path to the station is long.",
    "antonym": "kurz",
    "pronunciation_hint": "lang"
  },
  {
    "word": "neu",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "new",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Ich habe ein neues Fahrrad.",
    "example_sentence_en": "I have a new bicycle.",
    "antonym": "alt",
    "pronunciation_hint": "noy"
  },
  {
    "word": "schlecht",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "bad",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Das Wetter heute ist schlecht.",
    "example_sentence_en": "The weather today is bad.",
    "antonym": "gut",
    "pronunciation_hint": "shlecht"
  },
  {
    "word": "schön",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "beautiful / nice",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Einen schönen Tag noch!",
    "example_sentence_en": "Have a nice day!",
    "antonym": "hässlich / schlecht",
    "pronunciation_hint": "shoen"
  },
  {
    "word": "teuer",
    "word_class": "Adjektiv",
    "gender": "neutral",
    "plural": "",
    "english_translation": "expensive",
    "category": "Alltag (Adjektive)",
    "example_sentence_de": "Der Computer ist mir zu teuer.",
    "example_sentence_en": "The computer is too expensive for me.",
    "antonym": "billig",
    "pronunciation_hint": "toy-ehr"
  },

  # --- REISEN & MOBILITÄT ---
  {
    "word": "das Auto",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-s",
    "english_translation": "car",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Wir fahren mit dem Auto.",
    "example_sentence_en": "We are going by car.",
    "antonym": "",
    "pronunciation_hint": "ow-toe"
  },
  {
    "word": "der Bahnhof",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "¨-e",
    "english_translation": "train station",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Wo ist der Bahnhof?",
    "example_sentence_en": "Where is the station?",
    "antonym": "",
    "pronunciation_hint": "bahn-hohf"
  },
  {
    "word": "der Bus",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-se",
    "english_translation": "bus",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Der Bus kommt um zehn Uhr.",
    "example_sentence_en": "The bus arrives at ten o'clock.",
    "antonym": "",
    "pronunciation_hint": "boos"
  },
  {
    "word": "das Fahrrad",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "¨-er",
    "english_translation": "bicycle / bike",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Fährst du gerne Fahrrad?",
    "example_sentence_en": "Do you like riding a bike?",
    "antonym": "",
    "pronunciation_hint": "fahr-raht"
  },
  {
    "word": "das Flugzeug",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-e",
    "english_translation": "airplane / plane",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Das Flugzeug fliegt nach London.",
    "example_sentence_en": "The plane is flying to London.",
    "antonym": "",
    "pronunciation_hint": "floog-tsoyk"
  },
  {
    "word": "die Stadt",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "¨-e",
    "english_translation": "city / town",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "München ist eine schöne Stadt.",
    "example_sentence_en": "Munich is a beautiful city.",
    "antonym": "das Dorf",
    "pronunciation_hint": "shtat"
  },
  {
    "word": "das Ticket",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-s",
    "english_translation": "ticket",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Ich brauche ein Ticket für den Zug.",
    "example_sentence_en": "I need a ticket for the train.",
    "antonym": "",
    "pronunciation_hint": "tik-et"
  },
  {
    "word": "der Zug",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "¨-e",
    "english_translation": "train",
    "category": "Reisen & Mobilität",
    "example_sentence_de": "Der Zug hat heute Verspätung.",
    "example_sentence_en": "The train is delayed today.",
    "antonym": "",
    "pronunciation_hint": "tsoog"
  },

  # --- ARBEIT & BERUF ---
  {
    "word": "die Arbeit",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-en",
    "english_translation": "work / job",
    "category": "Arbeit & Beruf",
    "example_sentence_de": "Macht dir deine Arbeit Spaß?",
    "example_sentence_en": "Do you enjoy your work?",
    "antonym": "die Freizeit",
    "pronunciation_hint": "ahr-byt"
  },
  {
    "word": "der Arzt",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "¨-e",
    "english_translation": "doctor (male)",
    "category": "Arbeit & Beruf",
    "example_sentence_de": "Ich muss zum Arzt gehen.",
    "example_sentence_en": "I must go to the doctor.",
    "antonym": "der Patient",
    "pronunciation_hint": "ahrtst"
  },
  {
    "word": "die Ärztin",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "-nen",
    "english_translation": "doctor (female)",
    "category": "Arbeit & Beruf",
    "example_sentence_de": "Unsere Ärztin ist sehr nett.",
    "example_sentence_en": "Our doctor is very nice.",
    "antonym": "",
    "pronunciation_hint": "aertst-in"
  },
  {
    "word": "der Chef",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-s",
    "english_translation": "boss (male)",
    "category": "Arbeit & Beruf",
    "example_sentence_de": "Der Chef möchte mit dir sprechen.",
    "example_sentence_en": "The boss wants to speak with you.",
    "antonym": "der Angestellte",
    "pronunciation_hint": "shef"
  },
  {
    "word": "der Lehrer",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-",
    "english_translation": "teacher (male)",
    "category": "Arbeit & Beruf",
    "example_sentence_de": "Unser Lehrer erklärt alles sehr gut.",
    "example_sentence_en": "Our teacher explains everything very well.",
    "antonym": "der Schüler",
    "pronunciation_hint": "lay-rehr"
  },
  {
    "word": "der Termin",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-e",
    "english_translation": "appointment / meeting",
    "category": "Arbeit & Beruf",
    "example_sentence_de": "Ich habe einen Termin um 14 Uhr.",
    "example_sentence_en": "I have an appointment at 2 p.m.",
    "antonym": "",
    "pronunciation_hint": "tehr-meen"
  },

  # --- EINKAUFEN & KONSUM ---
  {
    "word": "das Brot",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-e",
    "english_translation": "bread",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Kaufst du bitte ein Brot?",
    "example_sentence_en": "Would you buy a loaf of bread, please?",
    "antonym": "",
    "pronunciation_hint": "broht"
  },
  {
    "word": "die Butter",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "",
    "english_translation": "butter",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Die Butter steht im Kühlschrank.",
    "example_sentence_en": "The butter is in the fridge.",
    "antonym": "",
    "pronunciation_hint": "boot-tehr"
  },
  {
    "word": "das Essen",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "-",
    "english_translation": "food / meal",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Das Essen ist fertig!",
    "example_sentence_en": "The meal is ready!",
    "antonym": "",
    "pronunciation_hint": "es-sen"
  },
  {
    "word": "das Geld",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "",
    "english_translation": "money",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Ich habe kein Geld dabei.",
    "example_sentence_en": "I don't have any money with me.",
    "antonym": "",
    "pronunciation_hint": "gelt"
  },
  {
    "word": "das Gemüse",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "",
    "english_translation": "vegetables",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Wir müssen frisches Gemüse kaufen.",
    "example_sentence_en": "We need to buy fresh vegetables.",
    "antonym": "das Fleisch",
    "pronunciation_hint": "geh-mue-zuh"
  },
  {
    "word": "die Milch",
    "word_class": "Nomen",
    "gender": "die",
    "plural": "",
    "english_translation": "milk",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Trinkst du deine Milch warm oder kalt?",
    "example_sentence_en": "Do you drink your milk hot or cold?",
    "antonym": "",
    "pronunciation_hint": "milch"
  },
  {
    "word": "das Obst",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "",
    "english_translation": "fruit",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Obst ist sehr gesund.",
    "example_sentence_en": "Fruit is very healthy.",
    "antonym": "",
    "pronunciation_hint": "ohpst"
  },
  {
    "word": "der Tee",
    "word_class": "Nomen",
    "gender": "der",
    "plural": "-s",
    "english_translation": "tea",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Ein Glas schwarzer Tee, bitte.",
    "example_sentence_en": "A glass of black tea, please.",
    "antonym": "",
    "pronunciation_hint": "tay"
  },
  {
    "word": "das Wasser",
    "word_class": "Nomen",
    "gender": "das",
    "plural": "",
    "english_translation": "water",
    "category": "Einkaufen & Konsum",
    "example_sentence_de": "Kann ich ein Glas Wasser haben?",
    "example_sentence_en": "Can I have a glass of water?",
    "antonym": "",
    "pronunciation_hint": "vas-sehr"
  },

  # --- ALLTAG GRAMMATIK & SONSTIGE ---
  {
    "word": "ich",
    "word_class": "Pronomen",
    "gender": "neutral",
    "plural": "",
    "english_translation": "I",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Ich wohne in Köln.",
    "example_sentence_en": "I live in Cologne.",
    "antonym": "",
    "pronunciation_hint": "ich"
  },
  {
    "word": "du",
    "word_class": "Pronomen",
    "gender": "neutral",
    "plural": "",
    "english_translation": "you (singular, informal)",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Wie heißt du?",
    "example_sentence_en": "What is your name?",
    "antonym": "",
    "pronunciation_hint": "doo"
  },
  {
    "word": "und",
    "word_class": "Konjunktion",
    "gender": "neutral",
    "plural": "",
    "english_translation": "and",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Michael und Sarah kommen heute.",
    "example_sentence_en": "Michael and Sarah are coming today.",
    "antonym": "",
    "pronunciation_hint": "oont"
  },
  {
    "word": "oder",
    "word_class": "Konjunktion",
    "gender": "neutral",
    "plural": "",
    "english_translation": "or",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Möchtest du Kaffee oder Tee?",
    "example_sentence_en": "Would you like coffee or tea?",
    "antonym": "",
    "pronunciation_hint": "oh-dehr"
  },
  {
    "word": "in",
    "word_class": "Präposition",
    "gender": "neutral",
    "plural": "",
    "english_translation": "in / into",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Wir wohnen in Deutschland.",
    "example_sentence_en": "We live in Germany.",
    "antonym": "aus",
    "pronunciation_hint": "in"
  },
  {
    "word": "aus",
    "word_class": "Präposition",
    "gender": "neutral",
    "plural": "",
    "english_translation": "from / out of",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Ich komme aus Frankreich.",
    "example_sentence_en": "I come from France.",
    "antonym": "in",
    "pronunciation_hint": "ows"
  },
  {
    "word": "Hallo!",
    "word_class": "Ausdruck",
    "gender": "neutral",
    "plural": "",
    "english_translation": "Hello!",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Hallo! Wie geht es dir?",
    "example_sentence_en": "Hello! How are you?",
    "antonym": "Tschüss!",
    "pronunciation_hint": "hal-loh"
  },
  {
    "word": "Guten Tag!",
    "word_class": "Ausdruck",
    "gender": "neutral",
    "plural": "",
    "english_translation": "Good day! / Hello!",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Guten Tag, Herr Müller.",
    "example_sentence_en": "Good day, Mr. Müller.",
    "antonym": "",
    "pronunciation_hint": "goo-ten tahk"
  },
  {
    "word": "Bitte",
    "word_class": "Ausdruck",
    "gender": "neutral",
    "plural": "",
    "english_translation": "Please / You're welcome",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Ein Kaffee, bitte.",
    "example_sentence_en": "A coffee, please.",
    "antonym": "Danke",
    "pronunciation_hint": "bit-tuh"
  },
  {
    "word": "Danke",
    "word_class": "Ausdruck",
    "gender": "neutral",
    "plural": "",
    "english_translation": "Thank you",
    "category": "Alltag (Grammatik & Sonstige)",
    "example_sentence_de": "Vielen Dank für deine Hilfe.",
    "example_sentence_en": "Thank you very much for your help.",
    "antonym": "Bitte",
    "pronunciation_hint": "dang-kuh"
  }
]

# Write validated raw JSON data with indentation
with open(TARGET_FILE, "w", encoding="utf-8") as f:
    json.dump(a1_words, f, indent=2, ensure_ascii=False)

print(f"Successfully generated {len(a1_words)} pristine Level A1 vocabulary words inside '{TARGET_FILE}'.")
